=== BlueBrain/hwloc/src/hwloc.dtd
<!ELEMENT root (object)+>
<!ATTLIST root complete_cpuset CDATA "" >
<!ATTLIST root online_cpuset CDATA "" >
<!ATTLIST root allowed_cpuset CDATA "" >

<!ELEMENT object (object)*>
<!ATTLIST object type (System | Machine | Misc | NUMANode | Socket| Cache | Core | Proc | Bridge | PCIDev) #REQUIRED>
<!ATTLIST object os_level CDATA "-1" >
<!ATTLIST object os_index CDATA "-1" >
<!ATTLIST object cpuset CDATA "0" >
<!ATTLIST object name CDATA "" >
<!ATTLIST object dmi_board_vendor CDATA "" >
<!ATTLIST object dmi_board_name CDATA "" >
<!ATTLIST object memory_kB CDATA "0" >
<!ATTLIST object huge_page_size_kB CDATA "0" >
<!ATTLIST object huge_page_free CDATA "0" >
<!ATTLIST object depth CDATA "-1" >
<!ATTLIST object bridge_type CDATA "" >
<!ATTLIST object bridge_pci CDATA "" >
<!ATTLIST object pci_busid CDATA "" >
<!ATTLIST object pci_type CDATA "" >

=== BlueBrain/hwloc/tests/xml/16amd64-8nd2c-cpusets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "hwloc.dtd">
<root offline_cpuset="0">
  <object type="System" os_level="-1" os_index="0" cpuset="0000f07f" dmi_board_vendor="TYAN Computer Corp" dmi_board_name="S4881 " memory_kB="0" huge_page_free="0" huge_page_size_kB="0">
    <object type="NUMANode" os_level="-1" os_index="0" cpuset="00000003" memory_kB="0" huge_page_free="0">
      <object type="Socket" os_level="-1" os_index="0" cpuset="00000003">
        <object type="Cache" os_level="-1" os_index="-1" cpuset="00000001" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="00000001" memory_kB="64" depth="1">
            <object type="Core" os_level="-1" os_index="0" cpuset="00000001">
              <object type="Proc" os_level="-1" os_index="0" cpuset="00000001"/>
            </object>
          </object>
        </object>
        <object type="Cache" os_level="-1" os_index="-1" cpuset="00000002" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="00000002" memory_kB="64" depth="1">
            <object type="Core" os_level="-1" os_index="1" cpuset="00000002">
              <object type="Proc" os_level="-1" os_index="1" cpuset="00000002"/>
            </object>
          </object>
        </object>
      </object>
    </object>
    <object type="NUMANode" os_level="-1" os_index="1" cpuset="0000000c" memory_kB="8388608" huge_page_free="0">
      <object type="Socket" os_level="-1" os_index="1" cpuset="0000000c">
        <object type="Cache" os_level="-1" os_index="-1" cpuset="00000004" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="00000004" memory_kB="64" depth="1">
            <object type="Core" os_level="-1" os_index="0" cpuset="00000004">
              <object type="Proc" os_level="-1" os_index="2" cpuset="00000004"/>
            </object>
          </object>
        </object>
        <object type="Cache" os_level="-1" os_index="-1" cpuset="00000008" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="00000008" memory_kB="64" depth="1">
            <object type="Core" os_level="-1" os_index="1" cpuset="00000008">
              <object type="Proc" os_level="-1" os_index="3" cpuset="00000008"/>
            </object>
          </object>
        </object>
      </object>
    </object>
    <object type="NUMANode" os_level="-1" os_index="2" cpuset="00000030" memory_kB="8388608" huge_page_free="0">
      <object type="Socket" os_level="-1" os_index="2" cpuset="00000030">
        <object type="Cache" os_level="-1" os_index="-1" cpuset="00000010" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="00000010" memory_kB="64" depth="1">
            <object type="Core" os_level="-1" os_index="0" cpuset="00000010">
              <object type="Proc" os_level="-1" os_index="4" cpuset="00000010"/>
            </object>
          </object>
        </object>
        <object type="Cache" os_level="-1" os_index="-1" cpuset="00000020" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="00000020" memory_kB="64" depth="1">
            <object type="Core" os_level="-1" os_index="1" cpuset="00000020">
              <object type="Proc" os_level="-1" os_index="5" cpuset="00000020"/>
            </object>
          </object>
        </object>
      </object>
    </object>
    <object type="NUMANode" os_level="-1" os_index="3" cpuset="00000040" memory_kB="8388608" huge_page_free="0">
      <object type="Socket" os_level="-1" os_index="3" cpuset="00000040">
        <object type="Cache" os_level="-1" os_index="-1" cpuset="00000040" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="00000040" memory_kB="64" depth="1">
            <object type="Core" os_level="-1" os_index="0" cpuset="00000040">
              <object type="Proc" os_level="-1" os_index="6" cpuset="00000040"/>
            </object>
          </object>
        </object>
      </object>
    </object>
    <object type="NUMANode" os_level="-1" os_index="6" cpuset="00003000" memory_kB="0" huge_page_free="0">
      <object type="Socket" os_level="-1" os_index="6" cpuset="00003000">
        <object type="Cache" os_level="-1" os_index="-1" cpuset="00001000" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="00001000" memory_kB="64" depth="1">
            <object type="Core" os_level="-1" os_index="0" cpuset="00001000">
              <object type="Proc" os_level="-1" os_index="12" cpuset="00001000"/>
            </object>
          </object>
        </object>
        <object type="Cache" os_level="-1" os_index="-1" cpuset="00002000" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="00002000" memory_kB="64" depth="1">
            <object type="Core" os_level="-1" os_index="1" cpuset="00002000">
              <object type="Proc" os_level="-1" os_index="13" cpuset="00002000"/>
            </object>
          </object>
        </object>
      </object>
    </object>
    <object type="NUMANode" os_level="-1" os_index="7" cpuset="0000c000" memory_kB="0" huge_page_free="0">
      <object type="Socket" os_level="-1" os_index="7" cpuset="0000c000">
        <object type="Cache" os_level="-1" os_index="-1" cpuset="00004000" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="00004000" memory_kB="64" depth="1">
            <object type="Core" os_level="-1" os_index="0" cpuset="00004000">
              <object type="Proc" os_level="-1" os_index="14" cpuset="00004000"/>
            </object>
          </object>
        </object>
        <object type="Cache" os_level="-1" os_index="-1" cpuset="00008000" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="00008000" memory_kB="64" depth="1">
            <object type="Core" os_level="-1" os_index="1" cpuset="00008000">
              <object type="Proc" os_level="-1" os_index="15" cpuset="00008000"/>
            </object>
          </object>
        </object>
      </object>
    </object>
    <object type="NUMANode" os_level="-1" os_index="4" cpuset="0" memory_kB="8388608" huge_page_free="0"/>
    <object type="NUMANode" os_level="-1" os_index="5" cpuset="0" memory_kB="8388608" huge_page_free="0"/>
  </object>
</root>

=== BlueBrain/hwloc/tests/xml/16em64t-4s2c2t-offlines.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "hwloc.dtd">
<root complete_cpuset="0x0001915b" online_cpuset="0x0000905b" allowed_cpuset="0x0000915b">
  <object type="System" os_level="-1" os_index="0" cpuset="0x0000905b" dmi_board_vendor="" dmi_board_name="" memory_kB="0" huge_page_free="0" huge_page_size_kB="0">
    <object type="Socket" os_level="-1" os_index="0" cpuset="0x00001011">
      <object type="Cache" os_level="-1" os_index="-1" cpuset="0x00001011" memory_kB="4096" depth="3">
        <object type="Cache" os_level="-1" os_index="-1" cpuset="0x00000001" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="0x00000001" memory_kB="16" depth="1">
            <object type="Core" os_level="-1" os_index="0" cpuset="0x00000001">
              <object type="Proc" os_level="-1" os_index="0" cpuset="0x00000001"/>
            </object>
          </object>
        </object>
        <object type="Cache" os_level="-1" os_index="-1" cpuset="0x00001010" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="0x00001010" memory_kB="16" depth="1">
            <object type="Core" os_level="-1" os_index="1" cpuset="0x00001010">
              <object type="Proc" os_level="-1" os_index="4" cpuset="0x00000010"/>
              <object type="Proc" os_level="-1" os_index="12" cpuset="0x00001000"/>
            </object>
          </object>
        </object>
      </object>
    </object>
    <object type="Socket" os_level="-1" os_index="1" cpuset="0x00000002">
      <object type="Cache" os_level="-1" os_index="-1" cpuset="0x00000002" memory_kB="4096" depth="3">
        <object type="Cache" os_level="-1" os_index="-1" cpuset="0x00000002" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="0x00000002" memory_kB="16" depth="1">
            <object type="Core" os_level="-1" os_index="0" cpuset="0x00000002">
              <object type="Proc" os_level="-1" os_index="1" cpuset="0x00000002"/>
            </object>
          </object>
        </object>
      </object>
    </object>
    <object type="Socket" os_level="-1" os_index="3" cpuset="0x00008008">
      <object type="Cache" os_level="-1" os_index="-1" cpuset="0x00008008" memory_kB="4096" depth="3">
        <object type="Cache" os_level="-1" os_index="-1" cpuset="0x00000008" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="0x00000008" memory_kB="16" depth="1">
            <object type="Core" os_level="-1" os_index="0" cpuset="0x00000008">
              <object type="Proc" os_level="-1" os_index="3" cpuset="0x00000008"/>
            </object>
          </object>
        </object>
        <object type="Cache" os_level="-1" os_index="-1" cpuset="0x00008000" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="0x00008000" memory_kB="16" depth="1">
            <object type="Core" os_level="-1" os_index="1" cpuset="0x00008000">
              <object type="Proc" os_level="-1" os_index="15" cpuset="0x00008000"/>
            </object>
          </object>
        </object>
      </object>
    </object>
    <object type="Socket" os_level="-1" os_index="2" cpuset="0x00000040">
      <object type="Cache" os_level="-1" os_index="-1" cpuset="0x00000040" memory_kB="4096" depth="3">
        <object type="Cache" os_level="-1" os_index="-1" cpuset="0x00000040" memory_kB="1024" depth="2">
          <object type="Cache" os_level="-1" os_index="-1" cpuset="0x00000040" memory_kB="16" depth="1">
            <object type="Core" os_level="-1" os_index="1" cpuset="0x00000040">
              <object type="Proc" os_level="-1" os_index="6" cpuset="0x00000040"/>
            </object>
          </object>
        </object>
      </object>
    </object>
  </object>
</root>
